# using Docker-Compose Version 3
version: '3'

services:
  telegraf-blueflood-translator:
    container_name: telegraf-blueflood-translator
    image: blueflood/telegraf-blueflood-translator
    ports:
      - "8090:8090"

  elasticsearch-consumer:
    container_name: elasticsearch-consumer
    image: blueflood/elasticsearch-consumer
    ports:
      - "8091:8091"

  cassandra-consumer:
    container_name: cassandra-consumer
    image: blueflood/cassandra-consumer
    ports:
      - "8092:8092"

  metrics-query-service:
    container_name: metrics-query-service
    image: blueflood/metrics-query-service
    ports:
      - "8093:8093"

  es-query-service:
    container_name: es-query-service
    image: blueflood/elasticsearch-query-service
    ports:
      - "8094:8094"
